### ISSUE TITLE
can you share your pre-trained models?

### ISSUE THREAD

**Issue by miiyqiii** [illidanlab/SplitMix#2]

**Comment by jyhong836** [comment]
Hi. Since we do not have enough space to share all models, please comment on which model you need.

**Comment by miiyqiii** [comment]
split-mix on cifar10

**Comment by jyhong836** [comment]
For the experiments defined by the file: `sweeps/fed_class_niid/cifar10_SplitMix.yaml`, please find the models at https://drive.google.com/drive/folders/1JkgtZfFUJlV-28oroaBcYpxbEYDxjSK5?usp=sharing
